# Generated by Django 5.1.7 on 2025-04-28 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_employee_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("user", "system")},
        ),
    ]
