# Generated by Django 5.1.7 on 2025-05-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_employee_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("waiter", "Waiter"),
                    ("chef", "Chef"),
                    ("delivery", "Delivery"),
                    ("maneger", "Maneger"),
                ],
                max_length=50,
            ),
        ),
    ]
