# Generated by Django 5.1.7 on 2025-05-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_employee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="system",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="system",
            name="subdomain",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
