# Generated by Django 5.1.7 on 2025-05-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_system_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="google_maps_link",
        ),
    ]
