# Generated by Django 5.1.7 on 2025-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_system_google_maps_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="custom_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
