# Generated by Django 5.1.7 on 2025-06-10 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_publicprofile_primary_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicprofile",
            name="system",
        ),
        migrations.AlterUniqueTogether(
            name="socialmedialink",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="system",
        ),
        migrations.RemoveIndex(
            model_name="publicsliderimage",
            name="core_public_system__8ccf6c_idx",
        ),
        migrations.RemoveIndex(
            model_name="publicsliderimage",
            name="core_public_is_acti_34e4a1_idx",
        ),
        migrations.RemoveField(
            model_name="publicsliderimage",
            name="link",
        ),
        migrations.AddField(
            model_name="system",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="public/logos/"),
        ),
        migrations.AddField(
            model_name="system",
            name="primary_color",
            field=models.CharField(default="#000000", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="public_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="public_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="secondary_color",
            field=models.CharField(default="#FFFFFF", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="social_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Format: {\n        "facebook": "url",\n        "instagram": "url",\n        "twitter": "url",\n        "linkedin": "url",\n        "youtube": "url",\n        "tiktok": "url"\n    }',
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name="system",
            index=models.Index(
                fields=["is_public"], name="core_system_is_publ_de83ce_idx"
            ),
        ),
        migrations.DeleteModel(
            name="PublicProfile",
        ),
        migrations.DeleteModel(
            name="SocialMediaLink",
        ),
    ]
