# Generated by Django 5.1.7 on 2025-06-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_create_restaurant_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RestaurantData",
        ),
    ]
