# Generated by Django 5.1.7 on 2025-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_system_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="design_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Format: {\n    "primaryColor": "#00bfff",\n    "secondaryColor": "#ffffff",\n    "background": "#ffffff",\n    "foreground": "#0a0a0a",\n    "border": "#e5e5e5",\n    "radius": "0.5rem"\n    }',
            ),
        ),
    ]
