# Generated by Django 5.0.2 on 2025-06-17 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_system_social_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicsliderimage",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="publicsliderimage",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publicsliderimage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
