# Generated by Django 5.0.2 on 2025-06-20 00:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_auto_20240618_0000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetotp",
            name="expires_at",
            field=models.DateTimeField(default=core.models.default_expiry),
        ),
    ]
