# Generated by Django 5.0.2 on 2025-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_passwordresetotp_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("waiter", "Waiter"),
                    ("chef", "Chef"),
                    ("delivery", "Delivery"),
                    ("manager", "Manager"),
                    ("head_chef", "Head Chef"),
                    ("cashier", "Cashier"),
                    ("inventory_manager", "Inventory Manager"),
                    ("cashier_supermarket", "Cashier (Supermarket)"),
                    ("manager_supermarket", "Manager (Supermarket)"),
                    (
                        "inventory_manager_supermarket",
                        "Inventory Manager (Supermarket)",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
