# Generated by Django 5.0.2 on 2025-06-22 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_twofatempsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twofatempsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
