# Generated by Django 5.0.2 on 2025-06-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_twofatempsession_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_confirm_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
