# Generated by Django 5.2 on 2025-04-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_unique_together'),
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.system'),
        ),
    ]
