# Generated by Django 4.1.2 on 2025-05-10 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_system_description_system_is_public_system_subdomain'),
        ('supermarket', '0006_remove_sale_created_at_remove_sale_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total_amount',
            new_name='vat_amount',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='price_at_sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.system'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supermarket.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('product', 'Product Discount'), ('order', 'Order Discount')], max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.product')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.system')),
            ],
        ),
    ]
