"""
Django settings for automation_system project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import dj_database_url

from datetime import timedelta
from pathlib import Path
from corsheaders.defaults import default_headers
# import renderers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+%24%sui+fq=vq(9h)cnuv7-j@nq5f)!vg6vzqa2fx2&z9^nmg"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.public.localhost']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
     'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # Core app (handles admin and shared models)
    'core',

    # Category apps (each representing a different type of system)
    'restaurant',
    # 'cafe',
    'supermarket',
    'workshop',
    'drf_yasg',
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",  # React development server
    "http://localhost:5173",  # React development server alternative
    "http://127.0.0.1:5174",  # React development server
    "http://localhost:5174",  # React development server alternative
    "http://127.0.0.1:5500" # React development server alternative
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-subdomain',  # Allow subdomain header
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5173",  # Trust frontend for CSRF
    "http://localhost:5173",  # Trust frontend for CSRF alternative
    "http://127.0.0.1:5174",  # Trust frontend for CSRF
    "http://localhost:5174",  # Trust frontend for CSRF alternative
    "http://127.0.0.1:5500" # Trust frontend for CSRF alternative
]
# Ensure cookie settings are correct (already set based on your headers)
# SESSION_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_SECURE = True


# Optional: Allow all origins (use only for development)
# CORS_ALLOW_ALL_ORIGINS = True


MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.subdomain.PublicSubdomainMiddleware',
]


ROOT_URLCONF = "automation_system.urls"


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # This enables the browsable API
    ],
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.SessionAuthentication',  # for managers (session-based)
#     )
}




TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / 'restaurant' / 'templates',
            BASE_DIR / 'core' / 'templates',
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "automation_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # required for deployment

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Create a function to ensure media directories exist
def create_media_dirs():
    media_dirs = [
        MEDIA_ROOT / 'public',
        MEDIA_ROOT / 'public' / 'logos',
        MEDIA_ROOT / 'public' / 'menus',
        MEDIA_ROOT / 'public' / 'sliders',
    ]
    for directory in media_dirs:
        directory.mkdir(parents=True, exist_ok=True)

# Call the function when Django starts
create_media_dirs()

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Add logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'middleware.subdomain': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'restaurant.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
