# Generated by Django 5.1.7 on 2025-05-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_employee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("waiter", "Waiter"),
                    ("chef", "Chef"),
                    ("delivery", "Delivery"),
                    ("manager", "Manager"),
                    ("head chef", "Head Chef"),
                ],
                max_length=50,
            ),
        ),
    ]
