# Generated by Django 5.1.7 on 2025-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_system_description_system_is_public_system_subdomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("waiter", "Waiter"),
                    ("chef", "Chef"),
                    ("delivery", "Delivery"),
                    ("manager", "Manager"),
                    ("head chef", "Head Chef"),
                    ("cashier", "Cashier"),
                    ("inventory_manager", "Inventory Manager"),
                ],
                max_length=50,
            ),
        ),
    ]
