# Generated by Django 5.1.7 on 2025-05-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_system_uuid"),
        ("core", "0013_system_uuid"),
    ]

    operations = []
