# Generated by Django 5.1.7 on 2025-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_system_created_at_system_custom_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="google_maps_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
