# Generated by Django 5.1.7 on 2025-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_system_google_maps_link_system_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
