# Generated by Django 5.1.7 on 2025-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_publicprofile_menu_file_publicprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicprofile",
            name="primary_color",
            field=models.CharField(default="#000000", max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="public_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="public_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="publicprofile",
            name="secondary_color",
            field=models.CharField(default="#FFFFFF", max_length=7, null=True),
        ),
    ]
