# Generated by Django 5.1.7 on 2025-06-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_publicprofile_system_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicsliderimage",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="publicsliderimage",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="ContactInformation",
        ),
        migrations.RemoveField(
            model_name="publicsliderimage",
            name="order",
        ),
    ]
