# Generated by Django 5.1.7 on 2025-03-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0003_order_status_order_table_number_order_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="system",
        ),
    ]
