# Generated by Django 5.1.7 on 2025-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("in_house", "In-House"), ("delivery", "Delivery")],
                default="in_house",
                help_text="Type of order. Default is in-house. Set to delivery only for delivery orders.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
