# Generated by Django 5.1.7 on 2025-06-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_delete_restaurantdata"),
        ("restaurant", "0012_alter_menuitem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_tables",
                    models.PositiveIntegerField(
                        default=15, help_text="Number of tables in the restaurant"
                    ),
                ),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_data",
                        to="core.system",
                    ),
                ),
            ],
        ),
    ]
