# Generated by Django 5.1.7 on 2025-06-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0014_create_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                help_text="Required for delivery orders",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True, help_text="Required for delivery orders", null=True
            ),
        ),
    ]
