# Generated by Django 4.1.2 on 2025-06-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0010_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='price',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
