# Generated by Django 4.1.2 on 2025-06-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0013_product_received_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
