# Generated by Django 5.0.2 on 2025-06-17 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket", "0018_populate_unit_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                default="pantry",
                help_text="Product category (default or custom)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="supermarket.product",
            ),
        ),
    ]
