# Generated by Django 5.0.2 on 2025-06-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarket", "0020_alter_saleitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                default="pantry",
                help_text="Product category (default or custom)",
                max_length=100,
            ),
        ),
    ]
