# Generated by Django 4.1.2 on 2025-06-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0021_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5),
        ),
    ]
