# Generated by Django 5.0.2 on 2025-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0022_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiving',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
