# Generated by Django 5.0.2 on 2025-06-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0024_product_description_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vat_rate',
        ),
    ]
