# Generated by Django 5.0.2 on 2025-06-20 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0025_remove_sale_vat_amount_remove_sale_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
