# Generated by Django 5.0.2 on 2025-06-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0026_remove_sale_discount_amount_sale_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
