# Generated by Django 5.1.7 on 2025-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_delete_restaurantdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
