# Generated by Django 5.1.7 on 2025-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_system_social_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="social_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Format: {\n        "facebook": "url",\n        "instagram": "url",\n        "twitter": "url",\n            "youtube": "url",\n        "tiktok": "url"\n    }',
            ),
        ),
    ]
