# Generated by Django 5.1.7 on 2025-04-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_menuitem_cost_order_profit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="profit",
        ),
    ]
