# Generated by Django 5.1.7 on 2025-05-01 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_employee_role"),
        ("restaurant", "0008_remove_order_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="waiter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.employee",
            ),
        ),
    ]
