# Generated by Django 5.1.7 on 2025-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0011_order_order_type_alter_menuitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/menu_images/"
            ),
        ),
    ]
