# Generated by Django 5.1.7 on 2025-06-14 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0015_order_customer_phone_order_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_best_deal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_special",
            field=models.BooleanField(default=False),
        ),
    ]
