# Generated by Django 5.2 on 2025-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0004_product_minimum_stock_stockchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchange',
            name='change_type',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10),
        ),
    ]
