# Generated by Django 4.1.2 on 2025-06-10 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0012_alter_product_stock_quantity_productbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='received_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
