# Generated by Django 4.1.2 on 2025-06-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0014_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='supermarket.product'),
        ),
    ]
